### ISSUE TITLE
Uploads via URL don't appear to handle non-200 status.

### ISSUE THREAD

**Issue by tomprince** [mozilla-services/tecken#1604]
Looking at the code [here](https://github.com/mozilla-services/tecken/blob/feff34034d5f2b903a0767c25a4745bb3802a2ef/tecken/upload/views.py#L220) it appears that there isn't any checking done that downloading the file provided succeeds before trying to process the file.

**Comment by peterbe** [comment]
It's true! Wanna throw in a quick PR to plug that. 

Mind you, the URL is carefully checked here: https://github.com/mozilla-services/tecken/blob/feff34034d5f2b903a0767c25a4745bb3802a2ef/tecken/upload/forms.py#L30

That's because it does a HEAD request and, I guess, optimistically assumes that if the HEAD request succeeded, the GET (stream) will succeed in the next couple of seconds.

**Comment by willkg** [comment]
Moving this to Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1669498
