### ISSUE TITLE
Handle FUNC vs. PUBLIC addresses more intelligently

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/tecken#926]
The current symbolication implementation parses the `.sym` files and picks out the addres/function from the lines that start with `FUNC` or `PUBLIC`. Then it merges these [here](https://github.com/mozilla-services/tecken/blob/36df3eed2dcb86703a612b5560f56677a4fd4f80/tecken/symbolicate/views.py#L756).

The only reason it does the `PUBLIC` *on top of* the `FUNC` is because of the origin of this code from [here](https://github.com/mozilla/Snappy-Symbolication-Server/blob/6a3347dc32d5ecaccaafd3219f341d7b7c2d0cf0/snappy/DiskCache_DiskCache.py#L380-L382).

**Comment by peterbe** [comment]
@luser how I wish I could do a needinfo? in GitHub :)

**Comment by luser** [comment]
Oh, looks like that was implemented because of [this comment](https://github.com/mozilla/Snappy-Symbolication-Server/issues/54#issuecomment-254881482). Unfortunately that's...backwards. :)

[`FUNC` records](https://chromium.googlesource.com/breakpad/breakpad/+/master/docs/symbol_files.md#records-3) describe a function and have a size associated, so it's possible to tell if an address actually does fall inside the function. They also usually have line records after them, so you can get the source file + line number for an address as well.

[`PUBLIC` records](https://chromium.googlesource.com/breakpad/breakpad/+/master/docs/symbol_files.md#records-4) describe an exported function and do *not* have a size associated, so the best you can do is find the closest `PUBLIC` symbol that's less than an address, which is often incorrect.

The Breakpad source that gets used for looking up symbols in the stackwalker in Socorro (sorry, it's C++) [is here](https://chromium.googlesource.com/breakpad/breakpad/+/b1226959a25b6a5311801d6f204b088c706e7c25/src/processor/basic_source_line_resolver.cc#228). It looks things up in the list of `FUNC` records first, then tries `PUBLIC` if it didn't find anything.

**Comment by peterbe** [comment]
Note-to-self; See also https://bugzilla.mozilla.org/show_bug.cgi?id=1470223

**Comment by willkg** [comment]
@peterbe I don't think we have any active plans along those lines.

**Comment by willkg** [comment]
I'm going to close this out. The current plan is to switch to Symbolic which parses sym files.

https://bugzilla.mozilla.org/show_bug.cgi?id=1636210
